[package]
name = "spellbook-server"
version = "0.1.0"
authors = ["coppa <sortal@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
